name: video_downloader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.0+5

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  animations: ^2.0.4
  google_mobile_ads: ^2.0.1
  another_flushbar: ^1.12.29
  percent_indicator: ^4.2.2
  youtube_player_flutter: ^8.1.0
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  path_provider: ^2.0.11
  youtube_explode_dart: ^1.12.0
  grouped_list: ^5.1.2
  visibility_detector: ^0.3.3
  lottie: ^1.4.3
  group_button: ^5.2.1
  loading_animation_widget: ^1.2.0+3
  share_plus: ^4.1.0
  auto_size_text: ^3.0.0
  animate_do: ^2.1.0
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  flex_color_picker: ^2.6.1
  flex_color_scheme: ^6.0.1
  syncfusion_flutter_sliders: ^20.3.49
  animated_text_kit: ^4.2.2
  package_info_plus: ^2.0.0
  liquid_pull_to_refresh: ^3.0.1
  google_nav_bar: ^5.0.6
  salomon_bottom_bar: ^3.3.1
  video_player: ^2.4.7
  chewie: ^1.3.5
  in_app_review: ^2.0.4
  ffmpeg_kit_flutter: 5.1.0
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0 
  change_app_package_name: ^1.1.0


flutter_icons:
  image_path: "assets/icons/launcher_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true  

flutter_native_splash:
  image: assets/icons/launcher_icon.png
  fullscreen: true
  color: "#F3F6F9"
  color_dark: "#071018"

flutter:
  assets: 
    - assets/icons/
    - assets/json/

  uses-material-design: true


