import 'package:google_fonts/google_fonts.dart';

import '../model/text_style_model.dart';

final List<AppTextStyleModels> appTextStyles = [
  AppTextStyleModels("aBeeZee", GoogleFonts.aBeeZee()),
  AppTextStyleModels("Abel", GoogleFonts.abel()),
  AppTextStyleModels("Abril Fatface", GoogleFonts.abrilFatface()),
  AppTextStyleModels("Aclonica", GoogleFonts.aclonica()),
  AppTextStyleModels("Acme", GoogleFonts.acme()),
  AppTextStyleModels("Actor", GoogleFonts.actor()),
  AppTextStyleModels("Adamina", GoogleFonts.adamina()),
  AppTextStyleModels("Advent Pro", GoogleFonts.adventPro()),
  AppTextStyleModels("Aguafina Script", GoogleFonts.aguafinaScript()),
  AppTextStyleModels("Akronim", GoogleFonts.akronim()),
  AppTextStyleModels("Aladin", GoogleFonts.aladin()),
  AppTextStyleModels("Alata", GoogleFonts.alata()),
  AppTextStyleModels("Alatsi", GoogleFonts.alatsi()),
  AppTextStyleModels("Aldrich", GoogleFonts.aldrich()),
  AppTextStyleModels("Alef", GoogleFonts.alef()),
  AppTextStyleModels("Alegreya", GoogleFonts.alegreya()),
  AppTextStyleModels("Alegreya SC", GoogleFonts.alegreyaSc()),
  AppTextStyleModels("Alegreya Sans", GoogleFonts.alegreyaSans()),
  AppTextStyleModels("Alegreya Sans SC", GoogleFonts.alegreyaSansSc()),
  AppTextStyleModels("Alex Brush", GoogleFonts.alexBrush()),
  AppTextStyleModels("Alfa Slab One", GoogleFonts.alfaSlabOne()),
  AppTextStyleModels("Alice", GoogleFonts.alice()),
  AppTextStyleModels("Alike", GoogleFonts.alike()),
  AppTextStyleModels("Alike Angular", GoogleFonts.alikeAngular()),
  AppTextStyleModels("Allan", GoogleFonts.allan()),
  AppTextStyleModels("Allerta", GoogleFonts.allerta()),
  AppTextStyleModels("Allerta Stencil", GoogleFonts.allertaStencil()),
  AppTextStyleModels("Allura", GoogleFonts.allura()),
  AppTextStyleModels("Almarai", GoogleFonts.almarai()),
  AppTextStyleModels("Almendra", GoogleFonts.almendra()),
  AppTextStyleModels("Almendra Display", GoogleFonts.almendraDisplay()),
  AppTextStyleModels("Almendra SC", GoogleFonts.almendraSc()),
  AppTextStyleModels("Amarante", GoogleFonts.amarante()),
  AppTextStyleModels("Amaranth", GoogleFonts.amaranth()),
  AppTextStyleModels("Amatic SC", GoogleFonts.amaticSc()),
  AppTextStyleModels("Amethysta", GoogleFonts.amethysta()),
  AppTextStyleModels("Amiko", GoogleFonts.amiko()),
  AppTextStyleModels("Amiri", GoogleFonts.amiri()),
  AppTextStyleModels("Amita", GoogleFonts.amita()),
  AppTextStyleModels("Anaheim", GoogleFonts.anaheim()),
  AppTextStyleModels("Andika", GoogleFonts.andika()),
  AppTextStyleModels("Angkor", GoogleFonts.angkor()),
  AppTextStyleModels(
      "Annie Use Your Telescope", GoogleFonts.annieUseYourTelescope()),
  AppTextStyleModels("Anonymous Pro", GoogleFonts.anonymousPro()),
  AppTextStyleModels("Antic", GoogleFonts.antic()),
  AppTextStyleModels("Antic Didone", GoogleFonts.anticDidone()),
  AppTextStyleModels("Antic Slab", GoogleFonts.anticSlab()),
  AppTextStyleModels("Anton", GoogleFonts.anton()),
  AppTextStyleModels("Arapey", GoogleFonts.arapey()),
  AppTextStyleModels("Arbutus", GoogleFonts.arbutus()),
  AppTextStyleModels("Arbutus Slab", GoogleFonts.arbutusSlab()),
  AppTextStyleModels("Architects Daughter", GoogleFonts.architectsDaughter()),
  AppTextStyleModels("Archivo", GoogleFonts.archivo()),
  AppTextStyleModels("Archivo Black", GoogleFonts.archivoBlack()),
  AppTextStyleModels("Archivo Narrow", GoogleFonts.archivoNarrow()),
  AppTextStyleModels("Aref Ruqaa", GoogleFonts.arefRuqaa()),
  AppTextStyleModels("Arima Madurai", GoogleFonts.arimaMadurai()),
  AppTextStyleModels("Arimo", GoogleFonts.arimo()),
  AppTextStyleModels("Arizonia", GoogleFonts.arizonia()),
  AppTextStyleModels("Armata", GoogleFonts.armata()),
  AppTextStyleModels("Arsenal", GoogleFonts.arsenal()),
  AppTextStyleModels("Artifika", GoogleFonts.artifika()),
  AppTextStyleModels("Arvo", GoogleFonts.arvo()),
  AppTextStyleModels("Arya", GoogleFonts.arya()),
  AppTextStyleModels("Asap", GoogleFonts.asap()),
  AppTextStyleModels("Asap Condensed", GoogleFonts.asapCondensed()),
  AppTextStyleModels("Asar", GoogleFonts.asar()),
  AppTextStyleModels("Asset", GoogleFonts.asset()),
  AppTextStyleModels("Assistant", GoogleFonts.assistant()),
  AppTextStyleModels("Astloch", GoogleFonts.astloch()),
  AppTextStyleModels("Asul", GoogleFonts.asul()),
  AppTextStyleModels("Athiti", GoogleFonts.athiti()),
  AppTextStyleModels("Atma", GoogleFonts.atma()),
  AppTextStyleModels("Atomic Age", GoogleFonts.atomicAge()),
  AppTextStyleModels("Aubrey", GoogleFonts.aubrey()),
  AppTextStyleModels("Audiowide", GoogleFonts.audiowide()),
  AppTextStyleModels("Autour One", GoogleFonts.autourOne()),
  AppTextStyleModels("Average", GoogleFonts.average()),
  AppTextStyleModels("Average Sans", GoogleFonts.averageSans()),
  AppTextStyleModels("Averia Gruesa Libre", GoogleFonts.averiaGruesaLibre()),
  AppTextStyleModels("Averia Libre", GoogleFonts.averiaLibre()),
  AppTextStyleModels("Averia Sans Libre", GoogleFonts.averiaSansLibre()),
  AppTextStyleModels("Averia Serif Libre", GoogleFonts.averiaSerifLibre()),
  AppTextStyleModels("Bad Script", GoogleFonts.badScript()),
  AppTextStyleModels("Bahiana", GoogleFonts.bahiana()),
  AppTextStyleModels("Bahianita", GoogleFonts.bahianita()),
  AppTextStyleModels("Bai Jamjuree", GoogleFonts.baiJamjuree()),
  AppTextStyleModels("Balthazar", GoogleFonts.balthazar()),
  AppTextStyleModels("Bangers", GoogleFonts.bangers()),
  AppTextStyleModels("Barlow", GoogleFonts.barlow()),
  AppTextStyleModels("Barlow Condensed", GoogleFonts.barlowCondensed()),
  AppTextStyleModels(
      "Barlow Semi Condensed", GoogleFonts.barlowSemiCondensed()),
  AppTextStyleModels("Barriecito", GoogleFonts.barriecito()),
  AppTextStyleModels("Barrio", GoogleFonts.barrio()),
  AppTextStyleModels("Basic", GoogleFonts.basic()),
  AppTextStyleModels("Baskervville", GoogleFonts.baskervville()),
  AppTextStyleModels("Battambang", GoogleFonts.battambang()),
  AppTextStyleModels("Baumans", GoogleFonts.baumans()),
  AppTextStyleModels("Bayon", GoogleFonts.bayon()),
  AppTextStyleModels("Belgrano", GoogleFonts.belgrano()),
  AppTextStyleModels("Bellefair", GoogleFonts.bellefair()),
  AppTextStyleModels("Belleza", GoogleFonts.belleza()),
  AppTextStyleModels("Bellota", GoogleFonts.bellota()),
  AppTextStyleModels("Bellota Text", GoogleFonts.bellotaText()),
  AppTextStyleModels("BenchNine", GoogleFonts.benchNine()),
  AppTextStyleModels("Bentham", GoogleFonts.bentham()),
  AppTextStyleModels("Berkshire Swash", GoogleFonts.berkshireSwash()),
  AppTextStyleModels("Bevan", GoogleFonts.bevan()),
  AppTextStyleModels("Bigelow Rules", GoogleFonts.bigelowRules()),
  AppTextStyleModels("Bigshot One", GoogleFonts.bigshotOne()),
  AppTextStyleModels("Bilbo", GoogleFonts.bilbo()),
  AppTextStyleModels("Bilbo Swash Caps", GoogleFonts.bilboSwashCaps()),
  AppTextStyleModels("BioRhyme", GoogleFonts.bioRhyme()),
  AppTextStyleModels("BioRhyme Expanded", GoogleFonts.bioRhymeExpanded()),
  AppTextStyleModels("Biryani", GoogleFonts.biryani()),
  AppTextStyleModels("Bitter", GoogleFonts.bitter()),
  AppTextStyleModels(
      "Black And White Picture", GoogleFonts.blackAndWhitePicture()),
  AppTextStyleModels("Black Han Sans", GoogleFonts.blackHanSans()),
  AppTextStyleModels("Black Ops One", GoogleFonts.blackOpsOne()),
  AppTextStyleModels("Blinker", GoogleFonts.blinker()),
  AppTextStyleModels("Bokor", GoogleFonts.bokor()),
  AppTextStyleModels("Bonbon", GoogleFonts.bonbon()),
  AppTextStyleModels("Boogaloo", GoogleFonts.boogaloo()),
  AppTextStyleModels("Bowlby One", GoogleFonts.bowlbyOne()),
  AppTextStyleModels("Brawler", GoogleFonts.brawler()),
  AppTextStyleModels("Bree Serif", GoogleFonts.breeSerif()),
  AppTextStyleModels("Bubblegum Sans", GoogleFonts.bubblegumSans()),
  AppTextStyleModels("Bubbler One", GoogleFonts.bubblerOne()),
  AppTextStyleModels("Buda", GoogleFonts.buda()),
  AppTextStyleModels("Buenard", GoogleFonts.buenard()),
  AppTextStyleModels("Bungee", GoogleFonts.bungee()),
  AppTextStyleModels("Bungee Hairline", GoogleFonts.bungeeHairline()),
  AppTextStyleModels("Bungee Inline", GoogleFonts.bungeeInline()),
  AppTextStyleModels("Bungee Outline", GoogleFonts.bungeeOutline()),
  AppTextStyleModels("Bungee Shade", GoogleFonts.bungeeShade()),
  AppTextStyleModels("Butcherman", GoogleFonts.butcherman()),
  AppTextStyleModels("Butterfly Kids", GoogleFonts.butterflyKids()),
  AppTextStyleModels("Cabin", GoogleFonts.cabin()),
  AppTextStyleModels("Cabin Condensed", GoogleFonts.cabinCondensed()),
  AppTextStyleModels("Cabin Sketch", GoogleFonts.cabinSketch()),
  AppTextStyleModels("Caesar Dressing", GoogleFonts.caesarDressing()),
  AppTextStyleModels("Cagliostro", GoogleFonts.cagliostro()),
  AppTextStyleModels("Cairo", GoogleFonts.cairo()),
  AppTextStyleModels("Caladea", GoogleFonts.caladea()),
  AppTextStyleModels("Calistoga", GoogleFonts.calistoga()),
  AppTextStyleModels("Calligraffitti", GoogleFonts.calligraffitti()),
  AppTextStyleModels("Cambay", GoogleFonts.cambay()),
  AppTextStyleModels("Cambo", GoogleFonts.cambo()),
  AppTextStyleModels("Candal", GoogleFonts.candal()),
  AppTextStyleModels("Cantarell", GoogleFonts.cantarell()),
  AppTextStyleModels("Cantata One", GoogleFonts.cantataOne()),
  AppTextStyleModels("Cantora One", GoogleFonts.cantoraOne()),
  AppTextStyleModels("Capriola", GoogleFonts.capriola()),
  AppTextStyleModels("Cardo", GoogleFonts.cardo()),
  AppTextStyleModels("Carme", GoogleFonts.carme()),
  AppTextStyleModels("Carrois Gothic", GoogleFonts.carroisGothic()),
  AppTextStyleModels("Carter One", GoogleFonts.carterOne()),
  AppTextStyleModels("Catamaran", GoogleFonts.catamaran()),
  AppTextStyleModels("Caudex", GoogleFonts.caudex()),
  AppTextStyleModels("Caveat", GoogleFonts.caveat()),
  AppTextStyleModels("Caveat Brush", GoogleFonts.caveatBrush()),
  AppTextStyleModels("Cedarville Cursive", GoogleFonts.cedarvilleCursive()),
  AppTextStyleModels("Ceviche One", GoogleFonts.cevicheOne()),
  AppTextStyleModels("Chakra Petch", GoogleFonts.chakraPetch()),
  AppTextStyleModels("Changa", GoogleFonts.changa()),
  AppTextStyleModels("Changa One", GoogleFonts.changaOne()),
  AppTextStyleModels("Chango", GoogleFonts.chango()),
  AppTextStyleModels("Charm", GoogleFonts.charm()),
  AppTextStyleModels("Charmonman", GoogleFonts.charmonman()),
  AppTextStyleModels("Chathura", GoogleFonts.chathura()),
  AppTextStyleModels("Chau Philomene One", GoogleFonts.chauPhilomeneOne()),
  AppTextStyleModels("Chela One", GoogleFonts.chelaOne()),
  AppTextStyleModels("Chelsea Market", GoogleFonts.chelseaMarket()),
  AppTextStyleModels("Chenla", GoogleFonts.chenla()),
  AppTextStyleModels("Cherry Cream Soda", GoogleFonts.cherryCreamSoda()),
  AppTextStyleModels("Cherry Swash", GoogleFonts.cherrySwash()),
  AppTextStyleModels("Chewy", GoogleFonts.chewy()),
  AppTextStyleModels("Chicle", GoogleFonts.chicle()),
  AppTextStyleModels("Chilanka", GoogleFonts.chilanka()),
  AppTextStyleModels("Chivo", GoogleFonts.chivo()),
  AppTextStyleModels("Chonburi", GoogleFonts.chonburi()),
  AppTextStyleModels("Cinzel", GoogleFonts.cinzel()),
  AppTextStyleModels("Cinzel Decorative", GoogleFonts.cinzelDecorative()),
  AppTextStyleModels("Clicker Script", GoogleFonts.clickerScript()),
  AppTextStyleModels("Coda", GoogleFonts.coda()),
  AppTextStyleModels("Coda Caption", GoogleFonts.codaCaption()),
  AppTextStyleModels("Codystar", GoogleFonts.codystar()),
  AppTextStyleModels("Coiny", GoogleFonts.coiny()),
  AppTextStyleModels("Combo", GoogleFonts.combo()),
  AppTextStyleModels("Comfortaa", GoogleFonts.comfortaa()),
  AppTextStyleModels("Comic Neue", GoogleFonts.comicNeue()),
  AppTextStyleModels("Coming Soon", GoogleFonts.comingSoon()),
  AppTextStyleModels("Concert One", GoogleFonts.concertOne()),
  AppTextStyleModels("Condiment", GoogleFonts.condiment()),
  AppTextStyleModels("Content", GoogleFonts.content()),
  AppTextStyleModels("Contrail One", GoogleFonts.contrailOne()),
  AppTextStyleModels("Convergence", GoogleFonts.convergence()),
  AppTextStyleModels("Cookie", GoogleFonts.cookie()),
  AppTextStyleModels("Copse", GoogleFonts.copse()),
  AppTextStyleModels("Corben", GoogleFonts.corben()),
  AppTextStyleModels("Cormorant", GoogleFonts.cormorant()),
  AppTextStyleModels("Cormorant Garamond", GoogleFonts.cormorantGaramond()),
  AppTextStyleModels("Cormorant Infant", GoogleFonts.cormorantInfant()),
  AppTextStyleModels("Cormorant SC", GoogleFonts.cormorantSc()),
  AppTextStyleModels("Cormorant Unicase", GoogleFonts.cormorantUnicase()),
  AppTextStyleModels("Cormorant Upright", GoogleFonts.cormorantUpright()),
  AppTextStyleModels("Courgette", GoogleFonts.courgette()),
  AppTextStyleModels("Courier Prime", GoogleFonts.courierPrime()),
  AppTextStyleModels("Cousine", GoogleFonts.cousine()),
  AppTextStyleModels("Coustard", GoogleFonts.coustard()),
  AppTextStyleModels("Covered By Your Grace", GoogleFonts.coveredByYourGrace()),
  AppTextStyleModels("Norican", GoogleFonts.norican()),
  AppTextStyleModels("Nosifer", GoogleFonts.nosifer()),
  AppTextStyleModels("Nothing You Could Do", GoogleFonts.nothingYouCouldDo()),
  AppTextStyleModels("Noticia Text", GoogleFonts.noticiaText()),
  AppTextStyleModels("Noto Sans", GoogleFonts.notoSans()),
  AppTextStyleModels("Noto Serif", GoogleFonts.notoSerif()),
  AppTextStyleModels("Nova Cut", GoogleFonts.novaCut()),
  AppTextStyleModels("Nova Flat", GoogleFonts.novaFlat()),
  AppTextStyleModels("Nova Mono", GoogleFonts.novaMono()),
  AppTextStyleModels("Nova Oval", GoogleFonts.novaOval()),
  AppTextStyleModels("Nova Round", GoogleFonts.novaRound()),
  AppTextStyleModels("Nova Script", GoogleFonts.novaScript()),
  AppTextStyleModels("Nova Slim", GoogleFonts.novaSlim()),
  AppTextStyleModels("Nova Square", GoogleFonts.novaSquare()),
  AppTextStyleModels("Numans", GoogleFonts.numans()),
  AppTextStyleModels("Nunito", GoogleFonts.nunito()),
  AppTextStyleModels("Nunito Sans", GoogleFonts.nunitoSans()),
  AppTextStyleModels("Odibee Sans", GoogleFonts.odibeeSans()),
  AppTextStyleModels("Odor Mean Chey", GoogleFonts.odorMeanChey()),
  AppTextStyleModels("Offside", GoogleFonts.offside()),
  AppTextStyleModels("Old Standard TT", GoogleFonts.oldStandardTt()),
  AppTextStyleModels("Oldenburg", GoogleFonts.oldenburg()),
  AppTextStyleModels("Oleo Script", GoogleFonts.oleoScript()),
  AppTextStyleModels(
      "Oleo Script Swash Caps", GoogleFonts.oleoScriptSwashCaps()),
  AppTextStyleModels("Open Sans", GoogleFonts.openSans()),
  AppTextStyleModels("Open Sans Condensed", GoogleFonts.openSansCondensed()),
  AppTextStyleModels("Oranienbaum", GoogleFonts.oranienbaum()),
  AppTextStyleModels("Orbitron", GoogleFonts.orbitron()),
  AppTextStyleModels("Oregano", GoogleFonts.oregano()),
  AppTextStyleModels("Orienta", GoogleFonts.orienta()),
  AppTextStyleModels("Original Surfer", GoogleFonts.originalSurfer()),
  AppTextStyleModels("Oswald", GoogleFonts.oswald()),
  AppTextStyleModels("Over the Rainbow", GoogleFonts.overTheRainbow()),
  AppTextStyleModels("Overlock", GoogleFonts.overlock()),
  AppTextStyleModels("Overlock SC", GoogleFonts.overlockSc()),
  AppTextStyleModels("Overpass", GoogleFonts.overpass()),
  AppTextStyleModels("Overpass Mono", GoogleFonts.overpassMono()),
  AppTextStyleModels("Ovo", GoogleFonts.ovo()),
  AppTextStyleModels("Oxygen", GoogleFonts.oxygen()),
  AppTextStyleModels("Oxygen Mono", GoogleFonts.oxygenMono()),
  AppTextStyleModels("PT Mono", GoogleFonts.ptMono()),
  AppTextStyleModels("PT Sans", GoogleFonts.ptSans()),
  AppTextStyleModels("PT Sans Caption", GoogleFonts.ptSansCaption()),
  AppTextStyleModels("PT Sans Narrow", GoogleFonts.ptSansNarrow()),
  AppTextStyleModels("PT Serif", GoogleFonts.ptSerif()),
  AppTextStyleModels("PT Serif Caption", GoogleFonts.ptSerifCaption()),
  AppTextStyleModels("Pacifico", GoogleFonts.pacifico()),
  AppTextStyleModels("Padauk", GoogleFonts.padauk()),
  AppTextStyleModels("Palanquin", GoogleFonts.palanquin()),
  AppTextStyleModels("Palanquin Dark", GoogleFonts.palanquinDark()),
  AppTextStyleModels("Pangolin", GoogleFonts.pangolin()),
  AppTextStyleModels("Paprika", GoogleFonts.paprika()),
  AppTextStyleModels("Parisienne", GoogleFonts.parisienne()),
  AppTextStyleModels("Passero One", GoogleFonts.passeroOne()),
  AppTextStyleModels("Passion One", GoogleFonts.passionOne()),
  AppTextStyleModels("Pathway Gothic One", GoogleFonts.pathwayGothicOne()),
  AppTextStyleModels("Patrick Hand", GoogleFonts.patrickHand()),
  AppTextStyleModels("Patrick Hand SC", GoogleFonts.patrickHandSc()),
  AppTextStyleModels("Pattaya", GoogleFonts.pattaya()),
  AppTextStyleModels("Patua One", GoogleFonts.patuaOne()),
  AppTextStyleModels("Pavanam", GoogleFonts.pavanam()),
  AppTextStyleModels("Paytone One", GoogleFonts.paytoneOne()),
  AppTextStyleModels("Peddana", GoogleFonts.peddana()),
  AppTextStyleModels("Peralta", GoogleFonts.peralta()),
  AppTextStyleModels("Permanent Marker", GoogleFonts.permanentMarker()),
  AppTextStyleModels("Petit Formal Script", GoogleFonts.petitFormalScript()),
  AppTextStyleModels("Petrona", GoogleFonts.petrona()),
  AppTextStyleModels("Philosopher", GoogleFonts.philosopher()),
  AppTextStyleModels("Piedra", GoogleFonts.piedra()),
  AppTextStyleModels("Pinyon Script", GoogleFonts.pinyonScript()),
  AppTextStyleModels("Pirata One", GoogleFonts.pirataOne()),
  AppTextStyleModels("Plaster", GoogleFonts.plaster()),
  AppTextStyleModels("Play", GoogleFonts.play()),
  AppTextStyleModels("Playball", GoogleFonts.playball()),
  AppTextStyleModels("Playfair Display", GoogleFonts.playfairDisplay()),
  AppTextStyleModels("Playfair Display SC", GoogleFonts.playfairDisplaySc()),
  AppTextStyleModels("Podkova", GoogleFonts.podkova()),
  AppTextStyleModels("Poiret One", GoogleFonts.poiretOne()),
  AppTextStyleModels("Poller One", GoogleFonts.pollerOne()),
  AppTextStyleModels("Poly", GoogleFonts.poly()),
  AppTextStyleModels("Pompiere", GoogleFonts.pompiere()),
  AppTextStyleModels("Pontano Sans", GoogleFonts.pontanoSans()),
  AppTextStyleModels("Poor Story", GoogleFonts.poorStory()),
  AppTextStyleModels("Poppins", GoogleFonts.poppins()),
  AppTextStyleModels("Port Lligat Sans", GoogleFonts.portLligatSans()),
  AppTextStyleModels("Port Lligat Slab", GoogleFonts.portLligatSlab()),
  AppTextStyleModels("Pragati Narrow", GoogleFonts.pragatiNarrow()),
  AppTextStyleModels("Prata", GoogleFonts.prata()),
  AppTextStyleModels("Preahvihear", GoogleFonts.preahvihear()),
  AppTextStyleModels("Press Start 2P", GoogleFonts.pressStart2p()),
  AppTextStyleModels("Pridi", GoogleFonts.pridi()),
  AppTextStyleModels("Princess Sofia", GoogleFonts.princessSofia()),
  AppTextStyleModels("Prociono", GoogleFonts.prociono()),
  AppTextStyleModels("Prompt", GoogleFonts.prompt()),
  AppTextStyleModels("Prosto One", GoogleFonts.prostoOne()),
  AppTextStyleModels("Proza Libre", GoogleFonts.prozaLibre()),
  AppTextStyleModels("Public Sans", GoogleFonts.publicSans()),
  AppTextStyleModels("Puritan", GoogleFonts.puritan()),
  AppTextStyleModels("Purple Purse", GoogleFonts.purplePurse()),
  AppTextStyleModels("Quando", GoogleFonts.quando()),
  AppTextStyleModels("Quantico", GoogleFonts.quantico()),
  AppTextStyleModels("Quattrocento", GoogleFonts.quattrocento()),
  AppTextStyleModels("Quattrocento Sans", GoogleFonts.quattrocentoSans()),
  AppTextStyleModels("Questrial", GoogleFonts.questrial()),
  AppTextStyleModels("Quicksand", GoogleFonts.quicksand()),
  AppTextStyleModels("Quintessential", GoogleFonts.quintessential()),
  AppTextStyleModels("Qwigley", GoogleFonts.qwigley()),
  AppTextStyleModels("Racing Sans One", GoogleFonts.racingSansOne()),
  AppTextStyleModels("Radley", GoogleFonts.radley()),
  AppTextStyleModels("Rajdhani", GoogleFonts.rajdhani()),
  AppTextStyleModels("Rakkas", GoogleFonts.rakkas()),
  AppTextStyleModels("Raleway", GoogleFonts.raleway()),
  AppTextStyleModels("Raleway Dots", GoogleFonts.ralewayDots()),
  AppTextStyleModels("Ramabhadra", GoogleFonts.ramabhadra()),
  AppTextStyleModels("Ramaraja", GoogleFonts.ramaraja()),
  AppTextStyleModels("Rambla", GoogleFonts.rambla()),
  AppTextStyleModels("Rammetto One", GoogleFonts.rammettoOne()),
  AppTextStyleModels("Ranchers", GoogleFonts.ranchers()),
  AppTextStyleModels("Rancho", GoogleFonts.rancho()),
  AppTextStyleModels("Ranga", GoogleFonts.ranga()),
  AppTextStyleModels("Rasa", GoogleFonts.rasa()),
  AppTextStyleModels("Rationale", GoogleFonts.rationale()),
  AppTextStyleModels("Ravi Prakash", GoogleFonts.raviPrakash()),
  AppTextStyleModels("Red Hat Display", GoogleFonts.redHatDisplay()),
  AppTextStyleModels("Red Hat Text", GoogleFonts.redHatText()),
  AppTextStyleModels("Redressed", GoogleFonts.redressed()),
  AppTextStyleModels("Reem Kufi", GoogleFonts.reemKufi()),
  AppTextStyleModels("Reenie Beanie", GoogleFonts.reenieBeanie()),
  AppTextStyleModels("Revalia", GoogleFonts.revalia()),
  AppTextStyleModels("Rhodium Libre", GoogleFonts.rhodiumLibre()),
  AppTextStyleModels("Ribeye", GoogleFonts.ribeye()),
  AppTextStyleModels("Ribeye Marrow", GoogleFonts.ribeyeMarrow()),
  AppTextStyleModels("Righteous", GoogleFonts.righteous()),
  AppTextStyleModels("Risque", GoogleFonts.risque()),
  AppTextStyleModels("Roboto", GoogleFonts.roboto()),
  AppTextStyleModels("Roboto Condensed", GoogleFonts.robotoCondensed()),
  AppTextStyleModels("Roboto Mono", GoogleFonts.robotoMono()),
  AppTextStyleModels("Roboto Slab", GoogleFonts.robotoSlab()),
  AppTextStyleModels("Rochester", GoogleFonts.rochester()),
  AppTextStyleModels("Rock Salt", GoogleFonts.rockSalt()),
  AppTextStyleModels("Rokkitt", GoogleFonts.rokkitt()),
  AppTextStyleModels("Romanesco", GoogleFonts.romanesco()),
  AppTextStyleModels("Ropa Sans", GoogleFonts.ropaSans()),
  AppTextStyleModels("Rosario", GoogleFonts.rosario()),
  AppTextStyleModels("Rosarivo", GoogleFonts.rosarivo()),
  AppTextStyleModels("Rouge Script", GoogleFonts.rougeScript()),
  AppTextStyleModels("Rozha One", GoogleFonts.rozhaOne()),
  AppTextStyleModels("Rubik", GoogleFonts.rubik()),
  AppTextStyleModels("Rubik Mono One", GoogleFonts.rubikMonoOne()),
  AppTextStyleModels("Ruda", GoogleFonts.ruda()),
];
