// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgJ_qaiOniFOPNisJMMMaKCIe_eIoMjUE',
    appId: '1:442667502219:web:8da719f558357ee887228e',
    messagingSenderId: '442667502219',
    projectId: 'video-downloader-5cc49',
    authDomain: 'video-downloader-5cc49.firebaseapp.com',
    storageBucket: 'video-downloader-5cc49.appspot.com',
    measurementId: 'G-6BYSLGX5KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXLlv-UdP0mUjnneuzy6gJIxdgUxVqzCM',
    appId: '1:442667502219:android:6685792d995529be87228e',
    messagingSenderId: '442667502219',
    projectId: 'video-downloader-5cc49',
    storageBucket: 'video-downloader-5cc49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADjXb9rRevkpO_Tkelxfubeh0XTKb38FY',
    appId: '1:442667502219:ios:a75ad5b2091a5b9987228e',
    messagingSenderId: '442667502219',
    projectId: 'video-downloader-5cc49',
    storageBucket: 'video-downloader-5cc49.appspot.com',
    iosClientId: '442667502219-eqri72tjdtcim48125uio3hl0h1kbani.apps.googleusercontent.com',
    iosBundleId: 'com.egemenerdem.videoDownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADjXb9rRevkpO_Tkelxfubeh0XTKb38FY',
    appId: '1:442667502219:ios:a75ad5b2091a5b9987228e',
    messagingSenderId: '442667502219',
    projectId: 'video-downloader-5cc49',
    storageBucket: 'video-downloader-5cc49.appspot.com',
    iosClientId: '442667502219-eqri72tjdtcim48125uio3hl0h1kbani.apps.googleusercontent.com',
    iosBundleId: 'com.egemenerdem.videoDownloader',
  );
}
